src/InitialConditions/distributions/dynamical_distribution.jl
test/nuclear_distributions.jl

The new "string" distribution was incorrectly giving the max index as the length of the string rather than the length of the data contained within the file. This has been fixed now.

Fix indexing of new distribution

---

src/Estimators.jl
src/NonadiabaticDistributions/dynamical_distribution.jl
src/NonadiabaticDistributions/harmonic_ring_polymer.jl
src/NonadiabaticDistributions/nuclear_distributions.jl
test/Core/calculators.jl
test/NonadiabaticDistributions/harmonic_ring_polymer.jl
test/runtests.jl

This uses the normal mode representation to generate the samples then converts them back to the primitive coordinate.

feat: add harmonic ring polymer distribution

---

src/DynamicsOutputs.jl
src/Ensembles/Ensembles.jl
src/Ensembles/reductions.jl
src/Ensembles/selections.jl
test/Ensembles/ensembles.jl
test/Ensembles/reductions.jl
test/Ensembles/selections.jl

The existing procedure involves attempting to use the saving callbacks from the single trajectory case similarly for the ensemble outputs as well. This was fine but it doesn't work when using EnsembleDistributed.
In this PR I've reworked the saving to instead rely up the standard diffeq output+reduction setup. This means it'll now work in parallel and the code is a bit cleaner.
The only downside is that it will require recalculation of some quantities such as forces after the trajectory has finished. But the ensemble workflow isn't really intended for that purpose so this should be fine.

Refactor ensemble outputs

---

src/Calculators/Calculators.jl
src/Calculators/friction.jl
src/Calculators/large_diabatic.jl
test/Core/calculators.jl
test/Dynamics/fssh.jl

This extra field can be used to check how many times each quantity is evaluated during a simulation. Useful for debugging and benchmarking. I also realise the `update_electronics!` functions were leading to some repeated evaluations so I have modified those to fix this.

Add `stats` field to calculators

---

src/NonadiabaticDistributions/harmonic_wigner.jl
test/NonadiabaticDistributions/harmonic_wigner.jl

Previously I had only used these where mass = 1 and the result is incorrect when using a different mass. This is fixed now.

fix: correct mass factor in harmonic wigner distributions

---

src/Calculators/Calculators.jl
src/Calculators/large_diabatic.jl
src/simulations.jl

NQCModels.jl now has a few more iterators we can use. We can now use these to iterate through states/electrons more easily.
I've also slightly rewritten the nonadiabatic coupling evaluation code for improved performance.

Use new iterators and small performance update

---

src/DynamicsMethods/ClassicalMethods/classical.jl
src/DynamicsMethods/DynamicsMethods.jl
src/DynamicsMethods/IntegrationAlgorithms/IntegrationAlgorithms.jl
src/DynamicsMethods/IntegrationAlgorithms/bcb.jl
src/DynamicsMethods/IntegrationAlgorithms/bcb_electronics.jl
src/DynamicsMethods/IntegrationAlgorithms/bcocb.jl
src/DynamicsMethods/IntegrationAlgorithms/mdef_baoab.jl
src/DynamicsMethods/IntegrationAlgorithms/mint.jl
src/DynamicsMethods/IntegrationAlgorithms/ringpolymer_mint.jl
src/DynamicsMethods/IntegrationAlgorithms/steps.jl
test/Dynamics/algorithms/bcb.jl
test/runtests.jl

- Previously adiabatic ring polymer dynamics defaulted to the VelocityVerlet algorithm. Now it will use the new BCB algorithm by default.
- All of the integration algorithms are declared at the top of the IntegrationAlgorithms module along with all the algorithm defaults.
- steps.jl contains a collection of some of the sub-steps used within a few different algorithms.

Add BCB algorithm for adiabatic ring polymer dynamics and refactor algorithm declarations

---

src/Calculators/Calculators.jl
src/Calculators/friction.jl
src/Calculators/large_diabatic.jl
src/Calculators/ring_polymer_large_diabatic.jl
src/DynamicsMethods/ClassicalMethods/ClassicalMethods.jl
src/DynamicsMethods/ClassicalMethods/diabatic_mdef.jl
src/DynamicsMethods/ClassicalMethods/mdef.jl
src/DynamicsMethods/ClassicalMethods/rpmdef.jl
src/DynamicsMethods/DynamicsMethods.jl
src/DynamicsMethods/IntegrationAlgorithms/bcocb.jl
src/DynamicsMethods/IntegrationAlgorithms/steps.jl
src/Estimators.jl
src/InitialConditions/ThermalMonteCarlo.jl
src/simulations.jl
test/Core/calculators.jl
test/Core/simulations.jl
test/Dynamics/classical.jl
test/Dynamics/diabatic_mdef.jl
test/Dynamics/mdef.jl
test/runtests.jl

This pull request includes lots of features related to MDEF simulations with model Hamiltonians.
- The old friction evaluation has been replaced with multiple choices of method.
- The DiabaticFrictionCalculators have been removed as they are no longer needed.
- A RingPolymerLargeDiabaticCalculator has been added to allow for ring polymer simulations of this type.

Update MDEF implementation for diabatic models

---

src/DynamicsOutputs.jl
src/InitialConditions/QuantisedDiatomic/QuantisedDiatomic.jl
src/InitialConditions/QuantisedDiatomic/binding_curve.jl

Includes handling for periodic copies of atoms for structures/simulations with a `PeriodicCell` to quantise a periodic copy with the shortest possible bond length. 
This fixes some occurrences of #292.

QuantiseDiatomic updates

---

src/DynamicsMethods/SurfaceHoppingMethods/surface_hopping.jl

during a frustrated hop in FSSH or IESH, the velocity along the NAC is inverted. 
currently, only rescaling=:off or rescaling=:standard are implemented. "Standard" refers to the 1990 Tully definition, where during a frustrated hop, the velocities are not changed.
rescaling=:vinversion inverts velocity along the NAC vector during a frustrated hop. This is standard practice in most modern surface hopping implementations as it helps with overcoherence in certain scenarios. It is also a crucial element for another SurfaceHopping method I plan to implement soon.

added new rescaling method ":vinversion" for SurfaceHopping

---

Project.toml
docs/src/initialconditions/metropolishastings.md
src/InitialConditions/ThermalMonteCarlo.jl

_2nd attempt at a PR without merging in extra stuff as well_
https://github.com/NQCD/NQCDynamics.jl/issues/320 was caused due to a breaking change in how AdvancedMH.jl handles the init_params keyword. initial_params is now required instead. I've removed compatibility for lower versions of AdvancedMH.jl to be safe.
https://github.com/NQCD/NQCDynamics.jl/issues/321 Has a non-breaking change to the movement-related keywords. Using the old move_ratio and internal_ratio will now produce a warning. Old keywords could be removed entirely after some time.

Update AdvancedMH.jl wrapper for Monte Carlo sampling. 

---

Project.toml
src/DynamicsOutputs.jl

It's like `OutputFinal`, but for the start of a trajectory. #innovation

Add OutputInitial DynamicsOutput

---

test/Core/calculators.jl

I'm not particularly proud of this "temporary" fix to the failing tests for `LargeDiabaticCalculator` and `RingPolymerLargeDiabaticCalculator`, but here we are. Until we decide on a better unit test to replace these ones, we can whitelist different values for different Julia versions.

Fix allocation-based unit tests

---

Project.toml
docs/src/atoms.md
test/Analysis/diatomic.jl

Removed ASEConvert.jl example since it includes unnecessary extra steps since James implemented the ase conversion functions. 
Replaced with an example for how to use PythonCall.jl to create an ase atoms object and how to convert it instead.

Update documentation for changes in NQCBase#11

---

src/DynamicsMethods/SurfaceHoppingMethods/SurfaceHoppingMethods.jl
src/DynamicsMethods/SurfaceHoppingMethods/fssh.jl
src/DynamicsMethods/SurfaceHoppingMethods/rpsh.jl

Moved the definitions of get_hopping_eigenvaues() to a more sensible location in SurfaceHoppingMethods()

Changed location of get_hopping_eigenvalues() to SurfaceHoppingMethods.jl

---

src/DynamicsMethods/SurfaceHoppingMethods/SurfaceHoppingMethods.jl
src/DynamicsMethods/SurfaceHoppingMethods/fssh.jl
src/DynamicsMethods/SurfaceHoppingMethods/rpsh.jl

Moved two generally applicable surface hopping functions get_hopping_nonadiabatic_coupling() and get_hopping_velocity() to SurfaceHoppingMethods.jl and moved their duplicate RingPolymer definitions to the same file to bring these definitions more in line with the duplicate function definition philosophy in the rest of NQCD

Moved general surface hopping functions to SurfaceHoppingMethods.jl

---

docs/src/NQCModels/combining_models.md
docs/src/dynamicssimulations/dynamicssimulations.md
docs/src/examples/mdef_multithermostat.md
src/NQCDynamics.jl
src/simulations.jl
test/Core/simulations.jl

This was necessary as “Thermostat” is technically incorrect, and “Temperature” is already taken by Unitful, which is often imported along with NQCDynamics.
I also managed to accidentally nuke the CI tests by forgetting to rename `Thermostat` to `Temperature` everywhere, but this time it should work.

Fix CI and rename Temperature to TemperatureSetting

---

src/DynamicsMethods/SurfaceHoppingMethods/SurfaceHoppingMethods.jl
src/DynamicsMethods/SurfaceHoppingMethods/fssh.jl
src/DynamicsMethods/SurfaceHoppingMethods/rpsh.jl

Moved get_hopping_velocity() and get_hopping_nonadiabatic_couplings() out of fssh.jl and into SurfaceHoppingMethods.jl. I have also moved their duplicate definitions for RingPolymerSimulations into the same file to bring these definitions inline with the philosophy for duplicate definitions used elsewhere in the code.

Moving general surface hopping functions to SurfaceHoppingMethods.jl

---

src/Analysis/diatomic.jl
src/structure.jl
test/Analysis/diatomic.jl

`Analysis.Diatomic.surface_distance_condition` was incorrectly calling `Analysis.Diatomic.surface_normal_height` without a `surface_normal` argument, which was included in a `symdiff` call to find all non-diatomic atom indices instead. 
This resulted in these atom indices being returned as `Float64`s, which caused indexing to fail down the line. 
Fixes #367.

Fix desorption checking logic in `Analysis.Diatomic`

---

.github/workflows/documentation.yml
docs/Project.toml
docs/make.jl
docs/src/NQCCalculators/overview.md
docs/src/NQCDistributions/overview.md
docs/src/NQCModels/analyticmodels.md
docs/src/NQCModels/combining_models.md
docs/src/NQCModels/frictionmodels.md
docs/src/NQCModels/overview.md
docs/src/api/NQCModels/adiabaticmodels.md
docs/src/api/NQCModels/diabaticmodels.md
docs/src/devdocs/models.md
docs/src/dynamicssimulations/dynamicsmethods/mdef.md
docs/src/getting_started.md
docs/src/index.md

updated some terminology in the docs and wrote some new code examples that work with the new code implementation

Ash baldwin docs changes

---

Project.toml
src/Project.toml

Fixes #427 temporarily, but we still need to solve various open issues anyway which will overwrite this change.

📍 OrdinaryDiffEq < 6.102.0 as a temporary fix
